# Generated by Django 5.1.3 on 2025-06-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CellType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=50, null=True)),
                ('recommended_seeding_density', models.PositiveIntegerField(help_text='Cells per cm²')),
            ],
        ),
        migrations.CreateModel(
            name='CultureVessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_format', models.CharField(max_length=100)),
                ('surface_area_cm2', models.FloatField(blank=True, null=True)),
                ('media_volume_per_well_ml', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
