# Generated by Django 4.2.5 on 2024-10-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('bulk_rna', 'Bulk RNA')], default='bulk_rna', max_length=50)),
                ('description', models.TextField()),
                ('linked_benchling_entry', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_visible_in_commercial_app', models.BooleanField(default=False)),
                ('metadata', models.JSONField()),
            ],
        ),
    ]
