# Generated by Django 4.2.5 on 2024-10-25 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bitbio_nucleus_bulk_rna', '0002_gene_analysisoutput_added_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('included_genes', models.ManyToManyField(blank=True, to='bitbio_nucleus_bulk_rna.gene')),
            ],
        ),
    ]
