# Generated by Django 4.2.5 on 2024-10-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitbio_nucleus_bulk_rna', '0003_genecollection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='long_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
