# Generated by Django 4.1 on 2024-11-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitbio_nucleus_bulk_rna', '0004_alter_gene_long_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisoutput',
            name='file_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='genecollection',
            name='linked_analyses',
            field=models.ManyToManyField(blank=True, to='bitbio_nucleus_bulk_rna.analysisoutput'),
        ),
    ]
