# Generated by Django 4.2.5 on 2024-12-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitbio_nucleus_bulk_rna', '0006_tier_usertier_usergenerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='genecollection',
            name='customer_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='genecollection',
            name='private_collection',
            field=models.BooleanField(default=True),
        ),
    ]
